### ISSUE TITLE
Couldn't find the 'node' binary

### ISSUE THREAD

**Issue by LETRA** [guishogt/alfred-spanish-synonyms#1]
Hola. He descargado tu workflow para Alfred (estaba esperando algo así desde que descubrí que no se puede usar Wordreference.com en esta app por limitaciones de la API) y me sale el siguiente mensaje cuando la inicio:

```
Couldn't find the 'node' binary

Symlink it to '/usr/local/bin'
```

Un saludo.

<img width="1064" alt="captura de pantalla 2018-07-01 a las 23 23 27" src="https://user-images.githubusercontent.com/16805254/42138982-58d5daf4-7d86-11e8-9a29-963f28d657eb.png">

**Comment by guishogt** [comment]
Hola,
Que bueno que te pones en contacto.
Te cuento, debes instalar node en tu mac.
Puedes bajarlo aqui https://nodejs.org/en/, sigues los pasos y listo. Luego
debería servir.

Cuéntame si lo lograste resolver para hacer las modificaciones y que a
otros les funcione mejor.

Saludos!

Luis
-- 
--
"The most beautiful thing we can experience is the mysterious. It is the
source of all true art and all science. He to whom this emotion is a
stranger, who can no longer pause to wonder and stand rapt in awe, is as
good as dead: his eyes are closed." (A. Einstein)

**Comment by LETRA** [comment]
Hola! Pues lo he descargado y funciona perfectamente. Felicidades por el programa, creo que le puede ser útil a mucha gente. Pero por favor haz un readme o algo para que la gente lo pueda usar cuando lo descargue. Hay gente que usamos Alfred pero no somos programadores ^^


Un saludo!

José Ramón

**Comment by lfernandez-xumak** [comment]
Que bien que funcionó bien. He agregado la nota para bajar npm.
Que lo disfrutes! :)

**Comment by guishogt** [comment]
Que bien que funcionó bien. He agregado la nota para bajar npm.
Que lo disfrutes! :)
